import Head from "next/head"
import Image from 'next/image'
import HeaderLink from '../components/HeaderLink'
import ExploreIcon from "@mui/icons-material/Explore"
import GroupIcon from "@mui/icons-material/Group"
import OndemandVideoSharpIcon from "@mui/icons-material/OndemandVideoSharp"
import BusinessCenterIcon from "@mui/icons-material/BusinessCenter"
import ArrowForwardIosRoundedIcon from "@mui/icons-material/ArrowForwardIosRounded"
import { getProviders, signIn } from 'next-auth/react'

const Home = ({ providers }) => {
    return (
        <div className='space-y-10 relative'>
            <Head>
                <title>LinkedIn</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className='flex justify-around items-center py-4'>
                <div className='relative w-36 h-10 '>
                    <Image src="/images/logo.svg" 
                        layout='fill' 
                        objectFit='contain' />
                </div>
                <div className='flex items-center sm:divide-x divide-gray-300'>
                    <div className='hidden sm:flex space-x-8 mr-4'>
                        <HeaderLink Icon={ExploreIcon} text="Discover" />
                        <HeaderLink Icon={GroupIcon} text="People" />
                        <HeaderLink Icon={OndemandVideoSharpIcon} text="Learning" />
                        <HeaderLink Icon={BusinessCenterIcon} text="Job" />
                    </div>
                    {Object.values(providers).map(provider => 
                        <div key={provider.name}>
                            <button className='text-blue-700 font-semibold rounded-full border border-blue-700 px-6 py-1.5 ml-4 transition ease-linear hover:shadow-[inset_0_0_0_1px] hover:shadow-blue-700 hover:bg-blue-100'
                                    onClick={() => signIn(provider.id, { callbackUrl: "/" })} >
                                Sign in
                            </button>
                        </div>    
                    )}
                </div>
            </header>

            <main className='flex flex-col xl:flex-row items-center max-w-screen-lg mx-auto'>
                <div className='space-y-6 xl:space-y-10'>
                    <h1 className='text-3xl md:text-5xl text-amber-800 max-w-xl !leading-snug px-4 xl:px-0'>
                        Welcome to your professional community
                    </h1>
                    <div className='space-y-4'>
                        <div className='intent'>
                            <h2 className='text-xl'>Search for a job</h2>
                            <ArrowForwardIosRoundedIcon className='text-gray-700' />
                        </div>
                        <div className='intent'>
                            <h2 className='text-xl'>Find a person you know</h2>
                            <ArrowForwardIosRoundedIcon className='text-gray-700' />
                        </div>
                        <div className='intent'>
                            <h2 className='text-xl'>Learn a new skill</h2>
                            <ArrowForwardIosRoundedIcon className='text-gray-700' />
                        </div>
                    </div>
                </div>

                <div className='relative xl:absolute w-80 h-80 xl:w-[650px] xl:h-[650px] top-14 right-5'>
                    <Image src="/images/login-image.svg" 
                        layout='fill'
                        objectFit='contain'
                        priority/>
                </div>
               
            </main>
        </div>
    )
}

export default Home

export async function getServerSideProps(context) {
    const providers = await getProviders()

    return {
        props: {
            providers
        }
    }
}